name: ci

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '22 4 * * *'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/docker-building/dashmachine:latest
      -
        name: Remove package versions
        uses: navikt/remove-package-versions@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          keep_versions: 4
